import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './mobile.css';
import './home.css';
import './legacy-home.css';
import './type.css';
import './transitions.css';
import './fixed-header.css';
import './full-image-pages.css';

const media='https://ivyleafec.com/wp-content/uploads/2024/06/';
const pages=[['Home','/'],['Programs','/programs'],['Why Ivy Leaf','/why-ivy-leaf'],['Enrollment','/enrollment'],['News','/news'],['Summer Camps','/summer-camps'],['Contact','/contact']];
const programs=['After-School Learning','Art Class','Piano Class','English','Chinese / Spanish','Dance','Speech & Debate'];
function Header({isHome}){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const update=()=>setScrolled(window.scrollY>28);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);return <header className={`${isHome?'home-header ':''}${scrolled?'scrolled':''}`}><a className="brand" href="/"><img src="https://ivyleafec.com/wp-content/uploads/2024/05/Leaf-Big-Logo-clearbg.png" alt="Ivy Leaf Education Center"/></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open}>Menu</button><nav className={open?'open':''}>{pages.map(([name,path])=><a href={path} onClick={()=>setOpen(false)}>{name}</a>)}</nav></header>}
function Enroll(){return <a className="button" href="/enrollment">Enroll Now</a>}
function TourForm(){const [sent,setSent]=useState(false);return <form className="footer-form" action="https://formsubmit.co/info@ivyleafec.com" method="POST" onSubmit={()=>setSent(true)}><h2>Schedule a Tour & Consulting</h2><input type="hidden" name="_subject" value="New Ivy Leaf tour request"/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_captcha" value="false"/><input required name="Parent name" placeholder="Parent name *"/><input name="Student name" placeholder="Student name"/><input required type="email" name="Email" placeholder="Email *"/><input name="Phone number" placeholder="Phone number"/><fieldset><legend>Preferred contact method</legend><label><input type="radio" name="Preferred contact" value="Call"/> Call</label><label><input type="radio" name="Preferred contact" value="Text"/> Text</label><label><input type="radio" name="Preferred contact" value="Email"/> Email</label></fieldset><textarea name="How can we assist you" placeholder="How can we assist you?"></textarea><button className="button" type="submit">Submit</button>{sent&&<small>Thank you — we’ll be in touch soon.</small>}</form>}
function Footer(){return <footer className="site-footer"><section className="footer-contact"><div><p className="eyebrow">Visit Ivy Leaf</p><h2>Ivy Leaf Education Center</h2><p>16469 Bernardo Center Dr<br/>San Diego, CA 92128</p><p><a href="tel:+18585995300">(858) 599-5300</a><br/><a href="mailto:info@ivyleafec.com">info@ivyleafec.com</a></p><p><b>Operation Hours</b><br/>Mon – Sat: 9:00 AM – 9:00 PM<br/>Sun: 9:00 AM – 6:00 PM</p></div><iframe title="Ivy Leaf Education Center location" src="https://www.google.com/maps?q=16469%20Bernardo%20Center%20Dr%2C%20San%20Diego%2C%20CA%2092128&output=embed" loading="lazy"/></section><TourForm/><p className="copyright">© {new Date().getFullYear()} Ivy Leaf Education Center</p></footer>}
function Home(){const cards=[['Our Programs','/programs','894fb2c0c15da58706d92a66f4082400-scaled.jpg'],['Why Ivy Leaf','/why-ivy-leaf','cb369dff1d1dde96859bfd215f412dfd.jpg'],['Enrollment','/enrollment','5ba25c011dbd56fbe91bd871c48dadfc.jpg'],['News','/news','4079e23ab55fed4b9cc4a240b865354d.jpg'],['Summer Camps','/summer-camps','Colorful-Modern-Playful-Organic-Kids-Summer-Camp-Flyer-4.png'],['Contact','/contact','8882a40f9696296b7c311e299af238fb.jpg']];return <><section className="hero"><div><h1>Welcome to Ivy Leaf Education Center!</h1><p>We inspire and empower K–12 students to excel in academics and pursue their passions.</p><a className="hero-button" href="/programs">Start Learning</a></div></section><section className="intro"><p className="eyebrow">A place to belong</p><h2>Let Us Guide You to Success</h2><p>Personalized guidance, joyful discovery, and a caring community for every learner.</p><div className="cards">{cards.map(([n,p,img])=><a href={p} style={{backgroundImage:`linear-gradient(0deg,rgba(15,45,34,.78),rgba(15,45,34,.05)),url(${media+img})`}}><strong>{n}</strong><span>Explore →</span></a>)}</div></section><section className="promise"><img src={media+'25e9a60336ac2151e0a6a88323bd46e4.jpg'}/><div><p className="eyebrow">Our approach</p><h2>Creative learning, caring guidance.</h2><p>From academic support to art, music, language, and enrichment, Ivy Leaf helps every child build confidence and discover what they love.</p><a href="/why-ivy-leaf" className="text-link">Discover Why Ivy Leaf →</a></div></section></>}
function Programs(){return <Page title="Our Programs" image="894fb2c0c15da58706d92a66f4082400-scaled.jpg"><h2>Welcome to Our Exciting After-School Learning Center</h2><p>We offer engaging, creative activities and an optional <b>pick-up service</b> for families.</p><div className="program-grid">{programs.map(x=><article><h3>{x}</h3><p>Encouraging confidence, curiosity, and new skills in a supportive setting.</p></article>)}</div><Enroll/></Page>}
function Why(){return <Page title="Why Ivy Leaf" image="cb369dff1d1dde96859bfd215f412dfd.jpg"><h2>Our Core Promise</h2><p>Ivy Leaf Education Center inspires children’s interest in learning through thoughtfully designed courses. We nurture character, artistic sensitivity, confidence, friendship, and healthy growth.</p><img className="piano" src={media+'25e9a60336ac2151e0a6a88323bd46e4.jpg'}/><h2>Our Teachers</h2><p>Our experienced teachers guide each child with skill, warmth, and individual attention.</p><h2>Our Campus</h2><p>A welcoming place designed for learning, creativity, and community.</p><Enroll/></Page>}
function Enrollment(){return <Page title="Enrollment" image="5ba25c011dbd56fbe91bd871c48dadfc.jpg"><h2>Welcome to join us!</h2><h3>After-School Schedule & Fees</h3><ul><li>Regular school day: 3 PM – 6 PM · $40/day</li><li>Short school day: 12 PM – 6 PM · $45/day</li><li>Holiday / full day: 9 AM – 6 PM · $75/day</li><li>Registration fee: $50 · Material fee: $50</li></ul><p>Please fill out the forms and email them to <a href="mailto:info@ivyleafec.com">info@ivyleafec.com</a>. We are happy to assist you.</p></Page>}
function News(){return <Page title="News" image="4079e23ab55fed4b9cc4a240b865354d.jpg"><h2>Events & News</h2><article><p className="eyebrow">Latest news</p><h3>Learning, creativity, and community at Ivy Leaf</h3><p>Check back for upcoming events and center news.</p></article><Enroll/></Page>}
function Camps(){return <Page title="Summer Camps" image="Colorful-Modern-Playful-Organic-Kids-Summer-Camp-Flyer-4.png"><h2>Experience Summer Fun at Ivy Leaf!</h2><p>Our summer camps spark curiosity, foster creativity, and encourage exploration.</p><Enroll/></Page>}
function Contact(){return <Page title="Contact" image="8882a40f9696296b7c311e299af238fb.jpg"><h2>Get in Touch</h2><p>We’re excited to meet your family and share the magic of Ivy Leaf Education Center. The center’s complete contact details, map, and tour request form are below.</p></Page>}
function Page({title,image,children}){return <><section className="page-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(22,58,48,.75),rgba(22,58,48,.15)),url(${media+image})`}}><h1>{title}</h1></section><main>{children}</main></>}
function App(){const [p,setPath]=useState(location.pathname);useEffect(()=>{const onPop=()=>setPath(location.pathname);const onLink=e=>{const link=e.target.closest('a[href]');if(!link||e.defaultPrevented||e.metaKey||e.ctrlKey||e.shiftKey||link.target||link.origin!==location.origin)return;const href=link.getAttribute('href');if(!href?.startsWith('/'))return;e.preventDefault();history.pushState({},'',href);setPath(href);window.scrollTo({top:0,behavior:'smooth'});};window.addEventListener('popstate',onPop);document.addEventListener('click',onLink);return()=>{window.removeEventListener('popstate',onPop);document.removeEventListener('click',onLink)}} ,[]);let C=p==='/programs'?Programs:p==='/why-ivy-leaf'?Why:p==='/enrollment'?Enrollment:p==='/news'?News:p==='/summer-camps'?Camps:p==='/contact'?Contact:Home;return <><Header isHome={p==='/'}/><div className="route-view" key={p}><C/></div><Footer/></>};
createRoot(document.getElementById('root')).render(<App/>);
